spring:
  mail:
    host: smtp.163.com
    username: nvj335537@163.com
    password: EDEUKSDOTYFZSOWD
  rabbitmq:
    addresses: 192.168.127.134
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefg
      expire: 7
  datasource:
    url: jdbc:mysql://192.168.127.134:3306/springboot
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  minio:
    endpoint: http://192.168.127.134:9000
    username: minio
    password: password
  weather:
    key: b6d5f378791847dfa3924d0591066424
  data:
    redis:
      host: 192.168.127.134
      port: 6379
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
